import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const translations: Record<Language, Record<string, string>> = {
    en: {
      // General
      'general.maqsam': 'Maqsam',
      'general.settings': 'Settings',
      'general.profile': 'Profile',
      'general.logout': 'Logout',
      'general.save': 'Save',
      'general.saveAndPublish': 'Save and publish',
      'general.saveDraft': 'Save Draft',
      'general.cancel': 'Cancel',
      'general.delete': 'Delete',
      'general.edit': 'Edit',
      'general.create': 'Create',
      'general.search': 'Search',
      'general.actions': 'Actions',
      'general.back': 'Back',
      'general.next': 'Next',
      'general.finish': 'Finish',
      'general.previous': 'Previous',
      'general.language': 'Language',
      'general.close': 'Close',
      'general.confirm': 'Confirm',
      'general.apply': 'Apply',
      'general.reset': 'Reset',
      
      // Sidebar
      'sidebar.agents': 'Agents',
      'sidebar.knowledgebase': 'Knowledge Base',
      'sidebar.pronunciation': 'Pronunciation Dictionary',
      
      // Agents Index
      'agents.title': 'AI Voice Agents',
      'agents.subtitle': 'Create and manage your AI voice agents',
      'agents.configSubtitle': 'Manage your AI voice agents and their configurations',
      'agents.createAgent': 'Create Agent',
      'agents.allAgents': 'All Agents',
      'agents.search': 'Search agents...',
      'agents.name': 'Agent Name',
      'agents.voice': 'Voice',
      'agents.language': 'Language',
      'agents.status': 'Status',
      'agents.state': 'State',
      'agents.created': 'Created',
      'agents.createdDate': 'Created Date',
      'agents.active': 'Active',
      'agents.inactive': 'Inactive',
      'agents.live': 'Live',
      'agents.draft': 'Draft',
      'agents.noAgents': 'No agents found',
      'agents.createFirst': 'Create your first agent to get started',
      'agents.calls': 'Calls',
      'agents.ivr': 'IVR',
      'agents.assignedNumbers': 'Assigned Numbers',
      'agents.assignNumber': 'Assign Number',
      'agents.testCall': 'Test Call',
      'agents.versionHistory': 'Version History',
      'agents.copyLink': 'Copy Agent Link',
      'agents.linkCopied': 'Link Copied!',
      'agents.goLive': 'Go Live',
      'agents.makeDraft': 'Make Draft',
      'agents.numOfCalls': 'Number of Calls',
      'agents.numOfCallsTooltip': 'This column represents the number of calls that this AI agent has successfully answered and handled',
      'agents.copied': 'Copied',
      'agents.copyAgentLink': 'Copy agent link',
      'agents.edit': 'Edit',
      'agents.versionHistoryAction': 'Version history',
      'agents.deleteAction': 'Delete',
      'agents.assignAndPublish': 'Assign Numbers and Publish',
      'agents.selectNumbers': 'Select phone numbers to assign to this agent',
      'agents.searchNumbers': 'Search phone numbers...',
      'agents.noNumbersFound': 'No phone numbers found',
      'agents.continue': 'Continue',
      'agents.confirmAndPublish': 'Confirm Assignment and Publish',
      'agents.publishDesc': 'Once the numbers are assigned, the AI agent will be published and set to live status.',
      'agents.numbersToAssign': 'Numbers to assign:',
      
      // Create Agent - Steps
      'createAgent.title': 'Create New Agent',
      'createAgent.editAgent': 'Edit Agent',
      'createAgent.step1': 'Agent Information',
      'createAgent.step2': 'Agent Behavior',
      'createAgent.step3': 'Company Information',
      'createAgent.step4': 'Prompt Review',
      'createAgent.published': 'Agent Published Successfully!',
      'createAgent.publishedDesc': 'Your AI voice agent is now live. Share this link to let users interact with your agent.',
      'createAgent.agentLink': 'Agent Link',
      
      // Agent Information Tab
      'agentInfo.title': 'Agent Profile',
      'agentInfo.subtitle': 'Define the agent\'s personality and characteristics',
      'agentInfo.agentName': 'Agent Name',
      'agentInfo.agentNamePlaceholder': 'e.g., Sarah, Alex, Jamie',
      'agentInfo.jobTitle': 'Job Title',
      'agentInfo.jobTitlePlaceholder': 'e.g., Customer Support Specialist',
      'agentInfo.timeZone': 'Time Zone',
      'agentInfo.selectTimeZone': 'Select time zone',
      'agentInfo.nationality': 'Nationality',
      'agentInfo.nationalityPlaceholder': 'e.g., American, British, etc',
      'agentInfo.personality': 'Personality',
      'agentInfo.personalityPlaceholder': 'Describe the agent\'s personality traits...',
      'agentInfo.aiVoice': 'Agent Voice',
      'agentInfo.aiVoiceSubtitle': 'Choose a voice model for your AI agent',
      'agentInfo.selectVoice': 'Select a voice',
      'agentInfo.voiceModel': 'Voice Model',
      'agentInfo.female': 'Female',
      'agentInfo.male': 'Male',
      'agentInfo.arabicEnglish': 'Arabic & English',
      'agentInfo.arabicOnly': 'Arabic',
      'agentInfo.listen': 'Listen',
      'agentInfo.selectDialect': 'Select a voice to see available languages and dialects.',
      'agentInfo.dialect': 'Dialect',
      'agentInfo.pronunciationDict': 'Pronunciation Dictionary',
      'agentInfo.pronunciationSubtitle': 'Upload pronunciation files to customize how the agent speaks specific words',
      'agentInfo.uploadFile': 'Upload File',
      'agentInfo.downloadSample': 'Download Sample',
      'agentInfo.uploadedFiles': 'Uploaded Files',
      'agentInfo.noFiles': 'No files uploaded yet',
      'agentInfo.fileName': 'File Name',
      'agentInfo.fileSize': 'Size',
      'agentInfo.uploadDate': 'Upload Date',
      'agentInfo.download': 'Download',
      'agentInfo.useGlobalDict': 'Use Global Pronunciation Dictionary',
      'agentInfo.useGlobalDictDesc': 'Include the predefined pronunciation dictionary from global settings',
      'agentInfo.customEntriesNote': 'Custom entries below will be added on top of the global dictionary. Custom pronunciations will take priority over global ones for matching words.',
      'agentInfo.uploadDictFile': 'Upload Pronunciation Dictionary File',
      'agentInfo.downloadFile': 'Download file',
      'agentInfo.deleteFile': 'Delete file',
      'agentInfo.addPronunciationEntry': 'Add Pronunciation Entry',
      'agentInfo.language': 'Language',
      'agentInfo.word': 'Word',
      'agentInfo.pronunciation': 'Pronunciation',
      'agentInfo.selectLanguage': 'Select language',
      'agentInfo.selectLanguageFirst': 'Select a language first',
      'agentInfo.addEntry': 'Add Entry',
      'agentInfo.noPronunciations': 'No pronunciations added yet. Select a language and add entries above.',
      'agentInfo.entry': 'entry',
      'agentInfo.entries': 'entries',
      'agentInfo.egyptianArabic': 'Egyptian Arabic',
      'agentInfo.saudiArabic': 'Saudi Arabic',
      'agentInfo.levantineArabic': 'Levantine Arabic',
      'agentInfo.maghrebiArabic': 'Maghrebi Arabic',
      'agentInfo.gulfArabic': 'Gulf Arabic',
      'agentInfo.modernStandardArabic': 'Modern Standard Arabic',
      'agentInfo.usEnglish': 'US English',
      'agentInfo.ukEnglish': 'UK English',
      
      // Agent Behavior Tab
      'agentBehavior.title': 'Agent Behavior',
      'agentBehavior.subtitle': 'Configure how your agent responds and behaves',
      'agentBehavior.greeting': 'Greeting',
      'agentBehavior.greetingPlaceholder': 'Enter the greeting message...',
      'agentBehavior.responseStyle': 'Response Style',
      'agentBehavior.responseStylePlaceholder': 'Describe how the agent should respond...',
      'agentBehavior.actions': 'Configure Actions',
      'agentBehavior.actionsSubtitle': 'Set up actions the agent can perform',
      'agentBehavior.addAction': 'Add Action',
      'agentBehavior.guardrails': 'Guardrails',
      'agentBehavior.guardrailsSubtitle': 'Set boundaries and safety measures for agent responses',
      'agentBehavior.defaultGuardrails': 'Default Guardrails',
      'agentBehavior.guardrailsDescription': 'Basic safety measures are enabled by default to ensure appropriate responses.',
      'agentBehavior.learnMore': 'Learn more',
      
      // Company Information Tab
      'companyInfo.title': 'Company Information',
      'companyInfo.subtitle': 'Provide details about your company',
      'companyInfo.companyName': 'Company Name',
      'companyInfo.companyNamePlaceholder': 'Enter company name',
      'companyInfo.industry': 'Industry',
      'companyInfo.industryPlaceholder': 'Select industry',
      'companyInfo.description': 'Company Description',
      'companyInfo.descriptionPlaceholder': 'Brief description of your company...',
      'companyInfo.businessHours': 'Business Hours',
      'companyInfo.businessHoursSubtitle': 'Set your operating hours (24-hour format)',
      'companyInfo.timezone': 'Timezone',
      'companyInfo.selectTimezone': 'Select timezone',
      'companyInfo.sunday': 'Sunday',
      'companyInfo.monday': 'Monday',
      'companyInfo.tuesday': 'Tuesday',
      'companyInfo.wednesday': 'Wednesday',
      'companyInfo.thursday': 'Thursday',
      'companyInfo.friday': 'Friday',
      'companyInfo.saturday': 'Saturday',
      'companyInfo.from': 'From',
      'companyInfo.to': 'To',
      
      // Prompt Review Tab / System Prompt Tab
      'promptReview.title': 'System Prompt Review',
      'promptReview.subtitle': 'Review and customize the system prompt',
      'promptReview.preview': 'Prompt Preview',
      'promptReview.edit': 'Edit Prompt',
      'promptReview.systemPromptTitle': 'System prompt',
      'promptReview.systemPromptDesc': 'The system prompt is used to determine the persona of the agent and the context of the conversation.',
      'promptReview.learnMore': 'Learn more',
      'promptReview.systemPromptLabel': 'System Prompt',
      'promptReview.systemPromptPlaceholder': 'Enter the system prompt...',
      'promptReview.systemPromptHelper': 'Define the agent\'s personality, environment, and tone to guide its behavior during conversations',
      
      // Knowledge Base
      'knowledgebase.title': 'Knowledge Base',
      'knowledgebase.subtitle': 'Manage your knowledge base resources',
      
      // Pronunciation Dictionary
      'pronunciation.title': 'Pronunciation Dictionary',
      'pronunciation.subtitle': 'Manage custom pronunciations',
      
      // File Upload
      'fileUpload.dragDrop': 'Drag and drop files here or click to browse',
      'fileUpload.accepted': 'Accepted formats: CSV, JSON',
      'fileUpload.maxSize': 'Max file size: 10MB',
      'fileUpload.uploadSuccess': 'File uploaded successfully',
      'fileUpload.uploadError': 'Error uploading file',
      'fileUpload.deleteSuccess': 'File deleted',
      'fileUpload.downloading': 'Downloading',
      'fileUpload.invalidFormat': 'Invalid file format. Please upload CSV or JSON files only.',
      'fileUpload.fileTooLarge': 'File is too large. Maximum size is 10MB.',
      
      // Modals
      'modal.assignNumber': 'Assign Phone Number',
      'modal.selectNumbers': 'Select phone numbers to assign to this agent',
      'modal.selectedNumbers': 'Selected Numbers',
      'modal.searchNumbers': 'Search phone numbers...',
      'modal.confirmAssign': 'Confirm Assignment',
      'modal.confirmMessage': 'Are you sure you want to assign the selected numbers to this agent?',
      'modal.phoneNumber': 'Phone Number',
      'modal.available': 'Available',
      'modal.inUse': 'In Use',
      
      // Toasts & Messages
      'toast.agentCreated': 'Agent created successfully',
      'toast.agentUpdated': 'Agent updated successfully',
      'toast.agentDeleted': 'Agent deleted successfully',
      'toast.statusChanged': 'Agent status changed',
      'toast.numbersAssigned': 'Phone numbers assigned successfully',
      
      // Knowledge Base Panel
      'kb.title': 'Knowledgebase Documents',
      'kb.subtitle': 'Upload and manage documents that train your AI agents',
      'kb.uploadDocument': 'Upload Document',
      'kb.documentName': 'Document Name',
      'kb.type': 'Type',
      'kb.size': 'Size',
      'kb.uploadedDate': 'Uploaded Date',
      'kb.download': 'Download',
      'kb.delete': 'Delete',
      'kb.cannotDelete': 'Cannot Delete Knowledge Base',
      'kb.docInUse': 'This document is currently in use',
      'kb.linkedMessage': 'The knowledge base',
      'kb.linkedMessageEnd': 'is currently linked to the following AI agent',
      'kb.linkedMessagePlural': 's',
      'kb.removeMessage': 'Please remove this knowledge base from all linked agents before attempting to delete it.',
      'kb.ok': 'OK',
      
      // Pronunciation Dictionary Panel
      'pd.title': 'Pronunciation Dictionary',
      'pd.subtitle': 'Manage custom pronunciations for your AI voice agents',
      'pd.export': 'Export',
      'pd.import': 'Import',
      'pd.uploadedFiles': 'Uploaded Files',
      'pd.uploadedFilesDesc': 'Search and manage pronunciation dictionary files',
      'pd.searchFiles': 'Search files...',
      'pd.fileName': 'File Name',
      'pd.size': 'Size',
      'pd.uploadDate': 'Upload Date',
      'pd.noFiles': 'No files found',
      'pd.download': 'Download',
      'pd.delete': 'Delete',
    },
    ar: {
      // General
      'general.maqsam': 'مقسم',
      'general.settings': 'الإعدادات',
      'general.profile': 'الملف الشخصي',
      'general.logout': 'تسجيل الخروج',
      'general.save': 'حفظ',
      'general.saveAndPublish': 'حفظ ونشر',
      'general.saveDraft': 'حفظ كمسودة',
      'general.cancel': 'إلغاء',
      'general.delete': 'حذف',
      'general.edit': 'تعديل',
      'general.create': 'إنشاء',
      'general.search': 'بحث',
      'general.actions': 'الإجراءات',
      'general.back': 'رجوع',
      'general.next': 'التالي',
      'general.finish': 'إنهاء',
      'general.previous': 'السابق',
      'general.language': 'اللغة',
      'general.close': 'إغلاق',
      'general.confirm': 'تأكيد',
      'general.apply': 'تطبيق',
      'general.reset': 'إعادة تعيين',
      
      // Sidebar
      'sidebar.agents': 'الوكلاء',
      'sidebar.knowledgebase': 'قاعدة المعرفة',
      'sidebar.pronunciation': 'قاموس النطق',
      
      // Agents Index
      'agents.title': 'وكلاء الصوت الذكي',
      'agents.subtitle': 'إنشاء وإدارة وكلاء الصوت الذكي',
      'agents.configSubtitle': 'إدارة وكلاء الصوت الذكي وإعداداتهم',
      'agents.createAgent': 'إنشاء وكيل',
      'agents.allAgents': 'جميع الوكلاء',
      'agents.search': 'البحث عن الوكلاء...',
      'agents.name': 'اسم الوكيل',
      'agents.voice': 'الصوت',
      'agents.language': 'اللغة',
      'agents.status': 'الحالة',
      'agents.state': 'الحالة',
      'agents.created': 'تاريخ الإنشاء',
      'agents.createdDate': 'تاريخ الإنشاء',
      'agents.active': 'نشط',
      'agents.inactive': 'غير نشط',
      'agents.live': 'مباشر',
      'agents.draft': 'مسودة',
      'agents.noAgents': 'لا توجد وكلاء',
      'agents.createFirst': 'أنشئ وكيلك الأول للبدء',
      'agents.calls': 'المك��لمات',
      'agents.ivr': 'الرد الصوتي التفاعلي',
      'agents.assignedNumbers': 'الأرقام المخصصة',
      'agents.assignNumber': 'تعيين رقم',
      'agents.testCall': 'مكالمة تجريبية',
      'agents.versionHistory': 'سجل الإصدارات',
      'agents.copyLink': 'نسخ رابط الوكيل',
      'agents.linkCopied': 'تم نسخ الرابط!',
      'agents.goLive': 'نشر',
      'agents.makeDraft': 'جعله مسودة',
      'agents.numOfCalls': 'عدد المكالمات',
      'agents.numOfCallsTooltip': 'يمثل هذا العمود عدد المكالمات التي أجاب عليها وكيل الذكاء الاصطناعي ونجح في التعامل معها',
      'agents.copied': 'تم النسخ',
      'agents.copyAgentLink': 'نسخ رابط الوكيل',
      'agents.edit': 'تعديل',
      'agents.versionHistoryAction': 'سجل الإصدارات',
      'agents.deleteAction': 'حذف',
      'agents.assignAndPublish': 'تعيين الأرقام والنشر',
      'agents.selectNumbers': 'اختر أرقام الهاتف لتعيينها لهذا الوكيل',
      'agents.searchNumbers': 'البحث عن أرقام الهاتف...',
      'agents.noNumbersFound': 'لم يتم العثور على أرقام هاتف',
      'agents.continue': 'متا��عة',
      'agents.confirmAndPublish': 'تأكيد التعيين والنشر',
      'agents.publishDesc': 'بمجرد تعيين الأرقام، سيتم نشر وكيل الذكاء الاصطناعي وتعيينه على الحالة المباشرة.',
      'agents.numbersToAssign': 'الأرقام المراد تعيينها:',
      
      // Create Agent - Steps
      'createAgent.title': 'إنشاء وكيل جديد',
      'createAgent.editAgent': 'تعديل الوكيل',
      'createAgent.step1': 'معلومات الوكيل',
      'createAgent.step2': 'سلوك الوكيل',
      'createAgent.step3': 'معلومات الشركة',
      'createAgent.step4': 'مراجعة الأمر',
      'createAgent.published': 'تم نشر الوكيل بنجاح!',
      'createAgent.publishedDesc': 'وكيل الصوت الذكي الخاص بك الآن مباشر. شارك هذا الرابط للسماح للمستخدمين بالتفاعل مع الوكيل.',
      'createAgent.agentLink': 'رابط الوكيل',
      
      // Agent Information Tab
      'agentInfo.title': 'ملف الوكيل',
      'agentInfo.subtitle': 'حدد شخصية الوكيل وخصائصه',
      'agentInfo.agentName': 'اسم الوكيل',
      'agentInfo.agentNamePlaceholder': 'مثال: سارة، أحمد، جميل',
      'agentInfo.jobTitle': 'المسمى الوظيفي',
      'agentInfo.jobTitlePlaceholder': 'مثال: أخصائي دعم العملاء',
      'agentInfo.timeZone': 'المنطقة الزمنية',
      'agentInfo.selectTimeZone': 'اختر المنطقة الزمنية',
      'agentInfo.nationality': 'الجنسية',
      'agentInfo.nationalityPlaceholder': 'مثال: أمريكي، بريطاني، إلخ',
      'agentInfo.personality': 'الشخصية',
      'agentInfo.personalityPlaceholder': 'صف سمات شخصية الوكيل...',
      'agentInfo.aiVoice': 'صوت الوكيل',
      'agentInfo.aiVoiceSubtitle': 'اختر نموذج الصوت لوكيل الذكاء الاصطناعي',
      'agentInfo.selectVoice': 'اختر صوتاً',
      'agentInfo.voiceModel': 'نموذج الصوت',
      'agentInfo.female': 'أنثى',
      'agentInfo.male': 'ذكر',
      'agentInfo.arabicEnglish': 'عربي وإنجليزي',
      'agentInfo.arabicOnly': 'عربي',
      'agentInfo.listen': 'استماع',
      'agentInfo.selectDialect': 'اختر صوتاً لرؤية اللغات واللهجات المتاحة.',
      'agentInfo.dialect': 'اللهجة',
      'agentInfo.pronunciationDict': 'قاموس النطق',
      'agentInfo.pronunciationSubtitle': 'قم بتحميل ملفات النطق لتخصيص طريقة نطق الوكيل لكل��ات معينة',
      'agentInfo.uploadFile': 'تحميل ملف',
      'agentInfo.downloadSample': 'تحميل نموذج',
      'agentInfo.uploadedFiles': 'الملفات المحملة',
      'agentInfo.noFiles': 'لم يتم تحميل أي ملفات بعد',
      'agentInfo.fileName': 'اسم الملف',
      'agentInfo.fileSize': 'الحجم',
      'agentInfo.uploadDate': 'تاريخ التحميل',
      'agentInfo.download': 'تحميل',
      'agentInfo.useGlobalDict': 'استخدام قاموس النطق العام',
      'agentInfo.useGlobalDictDesc': 'تضمين قاموس النطق المحدد مسبقاً من الإعدادات العامة',
      'agentInfo.customEntriesNote': 'سيتم إضافة الإدخالات المخصصة أدناه فوق القاموس العام. سيكون للنطق المخصص الأولوية على النطق العام للكلمات المطابقة.',
      'agentInfo.uploadDictFile': 'تحميل ملف قاموس النطق',
      'agentInfo.downloadFile': 'تحميل الملف',
      'agentInfo.deleteFile': 'حذف الملف',
      'agentInfo.addPronunciationEntry': 'إضافة إدخال نطق',
      'agentInfo.language': 'اللغة',
      'agentInfo.word': 'الكلمة',
      'agentInfo.pronunciation': 'النطق',
      'agentInfo.selectLanguage': 'اختر اللغة',
      'agentInfo.selectLanguageFirst': 'اختر اللغة أولاً',
      'agentInfo.addEntry': 'إضافة إدخال',
      'agentInfo.noPronunciations': 'لم تتم إضافة أي نطق بعد. اختر اللغة وأضف الإدخالات أعلاه.',
      'agentInfo.entry': 'إدخال',
      'agentInfo.entries': 'إدخالات',
      'agentInfo.egyptianArabic': 'اللهجة المصرية',
      'agentInfo.saudiArabic': 'اللهجة السعودية',
      'agentInfo.levantineArabic': 'اللهجة الشامية',
      'agentInfo.maghrebiArabic': 'اللهجة المغربية',
      'agentInfo.gulfArabic': 'اللهجة الخليجية',
      'agentInfo.modernStandardArabic': 'العربية الفصحى',
      'agentInfo.usEnglish': 'الإنجليزية الأمريكية',
      'agentInfo.ukEnglish': 'الإنجليزية البريطانية',
      
      // Agent Behavior Tab
      'agentBehavior.title': 'سلوك الوكيل',
      'agentBehavior.subtitle': 'قم بتكوين كيفية استجابة الوكيل وسلوكه',
      'agentBehavior.greeting': 'التحية',
      'agentBehavior.greetingPlaceholder': 'أدخل رسالة الترحيب...',
      'agentBehavior.responseStyle': 'أسلوب الرد',
      'agentBehavior.responseStylePlaceholder': 'صف كيف يجب على الوكيل الرد...',
      'agentBehavior.actions': 'تكوين الإجراءات',
      'agentBehavior.actionsSubtitle': 'قم بإعداد الإجراءات التي يمكن للوكيل تنفيذها',
      'agentBehavior.addAction': 'إضافة إجراء',
      'agentBehavior.guardrails': 'الضوابط',
      'agentBehavior.guardrailsSubtitle': 'تعيين الحدود وتدابير السلامة لاستجابات الوكيل',
      'agentBehavior.defaultGuardrails': 'الضوابط الافتراضية',
      'agentBehavior.guardrailsDescription': 'يتم تفعيل تدابير السلامة الأساسية بشكل افتراضي لضمان الردود المناسبة.',
      'agentBehavior.learnMore': 'معرفة المزيد',
      
      // Company Information Tab
      'companyInfo.title': 'معلومات الشركة',
      'companyInfo.subtitle': 'قدم تفاصيل حول شركتك',
      'companyInfo.companyName': 'اسم الشركة',
      'companyInfo.companyNamePlaceholder': 'أدخل اسم الشركة',
      'companyInfo.industry': 'الصناعة',
      'companyInfo.industryPlaceholder': 'اختر الصناعة',
      'companyInfo.description': 'وصف الشركة',
      'companyInfo.descriptionPlaceholder': 'وصف موجز لشركتك...',
      'companyInfo.businessHours': 'ساعات العمل',
      'companyInfo.businessHoursSubtitle': 'حدد ساعات العمل (تنسيق 24 ساعة)',
      'companyInfo.timezone': 'المنطقة الزمنية',
      'companyInfo.selectTimezone': 'اختر المنطقة الزمنية',
      'companyInfo.sunday': 'الأحد',
      'companyInfo.monday': 'الاثنين',
      'companyInfo.tuesday': 'الثلاثاء',
      'companyInfo.wednesday': 'الأربعاء',
      'companyInfo.thursday': 'الخميس',
      'companyInfo.friday': 'الجمعة',
      'companyInfo.saturday': 'السبت',
      'companyInfo.from': 'من',
      'companyInfo.to': 'إلى',
      
      // Prompt Review Tab / System Prompt Tab
      'promptReview.title': 'مراجعة أمر النظام',
      'promptReview.subtitle': 'راجع وخصص أمر النظام',
      'promptReview.preview': 'معاينة الأمر',
      'promptReview.edit': 'تعديل الأمر',
      'promptReview.systemPromptTitle': 'أمر النظام',
      'promptReview.systemPromptDesc': 'يُستخدم أمر النظام لتحديد شخصية الوكيل وسياق المحادثة.',
      'promptReview.learnMore': 'معرفة المزيد',
      'promptReview.systemPromptLabel': 'أمر النظام',
      'promptReview.systemPromptPlaceholder': 'أدخل أمر النظام...',
      'promptReview.systemPromptHelper': 'حدد شخصية الوكيل وبيئته وأسلوبه لتوجيه سلوكه أثناء المحادثات',
      
      // Knowledge Base
      'knowledgebase.title': 'قاعدة المعرفة',
      'knowledgebase.subtitle': 'إدارة موارد قاعدة المعرفة',
      
      // Pronunciation Dictionary
      'pronunciation.title': 'قاموس النطق',
      'pronunciation.subtitle': 'إدارة النطق المخصص',
      
      // File Upload
      'fileUpload.dragDrop': 'اسحب وأفلت الملفات هنا أو انقر للتصفح',
      'fileUpload.accepted': 'التنسيقات المقبولة: CSV، JSON',
      'fileUpload.maxSize': 'الحد الأقصى لحجم الملف: 10 ميجابايت',
      'fileUpload.uploadSuccess': 'تم تحميل الملف بنجاح',
      'fileUpload.uploadError': 'خطأ في تحميل الملف',
      'fileUpload.deleteSuccess': 'تم حذف الملف',
      'fileUpload.downloading': 'جارٍ التحميل',
      'fileUpload.invalidFormat': 'تنسيق ملف غير صالح. يرجى تحميل ملفات CSV أو JSON فقط.',
      'fileUpload.fileTooLarge': 'الملف كبير جداً. الحد الأقصى للحجم هو 10 ميجابايت.',
      
      // Modals
      'modal.assignNumber': 'تعيين رقم هاتف',
      'modal.selectNumbers': 'اختر أرقام الهاتف لتعيينها لهذا الوكيل',
      'modal.selectedNumbers': 'الأرقام المحددة',
      'modal.searchNumbers': 'البحث عن أرقام الهاتف...',
      'modal.confirmAssign': 'تأكيد التعيين',
      'modal.confirmMessage': 'هل أنت متأكد من أنك تريد تعيين الأرقام المحددة لهذا الوكيل؟',
      'modal.phoneNumber': 'رقم الهاتف',
      'modal.available': 'متاح',
      'modal.inUse': 'قيد الاستخدام',
      
      // Toasts & Messages
      'toast.agentCreated': 'تم إنشاء الوكيل بنجاح',
      'toast.agentUpdated': 'تم تحديث الوكيل بنجاح',
      'toast.agentDeleted': 'تم حذف الوكيل بنجاح',
      'toast.statusChanged': 'تم تغيير حالة الوكيل',
      'toast.numbersAssigned': 'تم تعيين أرقام الهاتف بنجاح',
      
      // Knowledge Base Panel
      'kb.title': 'مستندات قاعدة المعرفة',
      'kb.subtitle': 'قم بتحميل وإدارة المستندات التي تدرب وكلاء الذكاء الاصطناعي',
      'kb.uploadDocument': 'تحميل مستند',
      'kb.documentName': 'اسم المستند',
      'kb.type': 'النوع',
      'kb.size': 'الحجم',
      'kb.uploadedDate': 'تاريخ التحميل',
      'kb.download': 'تحميل',
      'kb.delete': 'حذف',
      'kb.cannotDelete': 'لا يمكن حذف قاعدة المعرفة',
      'kb.docInUse': 'هذا المستند قيد الاستخدام حالياً',
      'kb.linkedMessage': 'قاعدة المعرفة',
      'kb.linkedMessageEnd': 'مرتبطة حالياً بوكيل الذكاء الاصطناعي التالي',
      'kb.linkedMessagePlural': 'ة',
      'kb.removeMessage': 'يرجى إزالة قاعدة المعرفة هذه من جميع الوكلاء المرتبطين قبل محاولة حذفها.',
      'kb.ok': 'حسناً',
      
      // Pronunciation Dictionary Panel
      'pd.title': 'قاموس النطق',
      'pd.subtitle': 'إدارة النطق المخصص لوكلاء الصوت الذكي',
      'pd.export': 'تصدير',
      'pd.import': 'استيراد',
      'pd.uploadedFiles': 'الملفات المحملة',
      'pd.uploadedFilesDesc': 'البحث وإدارة ملفات قاموس النطق',
      'pd.searchFiles': 'البحث عن ملفات...',
      'pd.fileName': 'اسم الملف',
      'pd.size': 'الحجم',
      'pd.uploadDate': 'تاريخ التحميل',
      'pd.noFiles': 'لم يتم العثور على ملفات',
      'pd.download': 'تحميل',
      'pd.delete': 'حذف',
    },
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
